# Cargo.toml
[package]
name = "dns_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.35.0"
log = "0.4.27"
thiserror = "2.0.12"
env_logger = "0.11.8"
tokio = { version = "1.44", features = ["full"] }
hex = "0.4.3"
base64 = "0.22.1"
chrono = "0.4.41"
