version: '3.8'

services:
  dns:
    image: nx9-dns-server:latest
    container_name: nx9-dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data/dns.db:/var/nx9-dns-server/dns.db
      - ./keys:/etc/nx9-dns-server/keys
      - ./logs:/var/log/nx9-dns-server
    environment:
      - DNS_BIND=0.0.0.0:53
      - DNS_DB_PATH=/var/nx9-dns-server/dns.db
      - DNSSEC_KEY_FILE=/etc/nx9-dns-server/keys/Kanydomain.tld.key
      - DNS_FORWARDERS=8.8.8.8:53,1.1.1.1:53
      - DNS_NS_RECORDS=ns1.anydomain.tld.,ns2.anydomain.tld.
      - WEB_UI_BIND=0.0.0.0:8080
      - API_BIND=0.0.0.0:8081
    restart: unless-stopped